project_id = "rbmepcfznvcskxayuisp"

[functions.oauth-callback]
verify_jwt = true

[functions.oauth-refresh]
verify_jwt = true

[functions.validate-api-token]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.sync-notion-resources]
verify_jwt = true
