project_id = "rbmepcfznvcskxayuisp"

[functions.oauth-callback]
verify_jwt = true

[functions.oauth-refresh]
verify_jwt = true

[functions.validate-api-token]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true
import_map = "./functions/send-invitation/deno.json"
